import { Component } from '@angular/core';
import { ColorOrangeDirective, TranslateYDirective, TextDecorationLineDirective, PaddingLeftDirective, WidthDirective, TransitionPropertyDirective, PaddingBottomDirective, HeightDirective, BackgroundZincColorDirective, FontSizeDirective, MaxWScreenDirective, MarginLeftDirective, BackgroundOrangeColorDirective, FontFamilyDirective, AlignItemsDirective, TopDirective, JustifyContentDirective, ColorNeutralDirective, PositionDirective, LineHeightDirective, MarginBottomDirective, TextTransformDirective, TextAlignDirective, FlexWrapDirective, FontStyleDirective, TransitionTimingFunctionDirective, PaddingTopDirective, VerticalAlignDirective, MaxWidthDirective, MarginTopDirective, TransitionDurationDirective, FlexGrowDirective, RightDirective, FlexShrinkDirective, RotateDirective, FontWeightDirective, ZIndexDirective, FlexDirectionDirective, PaddingRightDirective, OpacityDirective, ColorZincDirective, ColumnGapDirective, DisplayDirective, ColorDirective, OverflowDirective, LeftDirective, MixBlendModeDirective, MarginRightDirective, CursorDirective, RowGapDirective, BackgroundColorDirective, BottomDirective, ScaleDirective, FlexBasisDirective } from '@public-repo/tailwindcss';

@Component({
  selector: 'sg-section_six',
  templateUrl: './section_six.component.html',
  standalone: true,
  imports: [ColorOrangeDirective, TranslateYDirective, TextDecorationLineDirective, PaddingLeftDirective, WidthDirective, TransitionPropertyDirective, PaddingBottomDirective, HeightDirective, BackgroundZincColorDirective, FontSizeDirective, MaxWScreenDirective, MarginLeftDirective, BackgroundOrangeColorDirective, FontFamilyDirective, AlignItemsDirective, TopDirective, JustifyContentDirective, ColorNeutralDirective, PositionDirective, LineHeightDirective, MarginBottomDirective, TextTransformDirective, TextAlignDirective, FlexWrapDirective, FontStyleDirective, TransitionTimingFunctionDirective, PaddingTopDirective, VerticalAlignDirective, MaxWidthDirective, MarginTopDirective, TransitionDurationDirective, FlexGrowDirective, RightDirective, FlexShrinkDirective, RotateDirective, FontWeightDirective, ZIndexDirective, FlexDirectionDirective, PaddingRightDirective, OpacityDirective, ColorZincDirective, ColumnGapDirective, DisplayDirective, ColorDirective, OverflowDirective, LeftDirective, MixBlendModeDirective, MarginRightDirective, CursorDirective, RowGapDirective, BackgroundColorDirective, BottomDirective, ScaleDirective, FlexBasisDirective]
})
export class SectionSixComponent {}