import { Component } from '@angular/core';
import { BorderTopWidthDirective, BorderRadiusDirective, TranslateYDirective, PaddingLeftDirective, WidthDirective, ColorBlueDirective, TransitionPropertyDirective, BackgroundNeutralColorDirective, PaddingBottomDirective, BackgroundZincColorDirective, FontSizeDirective, MaxWScreenDirective, MarginLeftDirective, AlignItemsDirective, TopDirective, BackgroundOrangeColorDirective, FontFamilyDirective, BackgroundSlateColorDirective, JustifyContentDirective, ColorNeutralDirective, PositionDirective, LineHeightDirective, MarginBottomDirective, TextTransformDirective, TextAlignDirective, BorderBottomRightRadiusDirective, FlexWrapDirective, TransitionTimingFunctionDirective, PaddingTopDirective, VerticalAlignDirective, MaxWidthDirective, MarginTopDirective, TransitionDurationDirective, BorderStyleDirective, BorderWidthDirective, FlexGrowDirective, BoxShadowDirective, FlexShrinkDirective, RotateDirective, BorderTopLeftRadiusDirective, ZIndexDirective, FontWeightDirective, FlexDirectionDirective, PaddingRightDirective, OpacityDirective, ColorZincDirective, ColumnGapDirective, DisplayDirective, ColorDirective, OverflowDirective, LeftDirective, MarginRightDirective, BorderTopRightRadiusDirective, RowGapDirective, CursorDirective, BorderBottomLeftRadiusDirective, BottomDirective, ScaleDirective, FlexBasisDirective } from '@public-repo/tailwindcss';

@Component({
  selector: 'sg-installation_section',
  templateUrl: './installation_section.component.html',
  standalone: true,
  imports: [BorderTopWidthDirective, BorderRadiusDirective, TranslateYDirective, PaddingLeftDirective, WidthDirective, ColorBlueDirective, TransitionPropertyDirective, BackgroundNeutralColorDirective, PaddingBottomDirective, BackgroundZincColorDirective, FontSizeDirective, MaxWScreenDirective, MarginLeftDirective, AlignItemsDirective, TopDirective, BackgroundOrangeColorDirective, FontFamilyDirective, BackgroundSlateColorDirective, JustifyContentDirective, ColorNeutralDirective, PositionDirective, LineHeightDirective, MarginBottomDirective, TextTransformDirective, TextAlignDirective, BorderBottomRightRadiusDirective, FlexWrapDirective, TransitionTimingFunctionDirective, PaddingTopDirective, VerticalAlignDirective, MaxWidthDirective, MarginTopDirective, TransitionDurationDirective, BorderStyleDirective, BorderWidthDirective, FlexGrowDirective, BoxShadowDirective, FlexShrinkDirective, RotateDirective, BorderTopLeftRadiusDirective, ZIndexDirective, FontWeightDirective, FlexDirectionDirective, PaddingRightDirective, OpacityDirective, ColorZincDirective, ColumnGapDirective, DisplayDirective, ColorDirective, OverflowDirective, LeftDirective, MarginRightDirective, BorderTopRightRadiusDirective, RowGapDirective, CursorDirective, BorderBottomLeftRadiusDirective, BottomDirective, ScaleDirective, FlexBasisDirective]
})
export class InstallationSectionComponent {}