import { Component } from '@angular/core';
import { BrightnessDirective, TransformOriginDirective, TranslateYDirective, TextDecorationLineDirective, PaddingLeftDirective, WidthDirective, ColorBlueDirective, BackgroundPositionDirective, TransitionPropertyDirective, FlexBasisDirective, PaddingBottomDirective, BackgroundClipDirective, FontSizeDirective, BorderBottomWidthDirective, MaxWScreenDirective, MarginLeftDirective, BackgroundOrangeColorDirective, AlignItemsDirective, BackgroundSizeDirective, JustifyContentDirective, ColorNeutralDirective, PositionDirective, LineHeightDirective, MarginBottomDirective, TextTransformDirective, TextAlignDirective, SaturateDirective, FlexWrapDirective, ScaleYDirective, HueRotateDirective, InvertDirective, TransitionTimingFunctionDirective, PaddingTopDirective, VerticalAlignDirective, MaxWidthDirective, TransitionDurationDirective, MarginTopDirective, BorderStyleDirective, ContrastDirective, FlexGrowDirective, SepiaDirective, BorderBottomZincColorDirective, BackgroundImageDirective, FlexShrinkDirective, BackgroundRepeatDirective, GradientFromPositionDirective, PaddingRightDirective, OpacityDirective, ColorZincDirective, ColumnGapDirective, DisplayDirective, ColorDirective, OverflowDirective, MarginRightDirective, RowGapDirective, GradientFromOrangeDirective, FontWeightDirective } from '@public-repo/tailwindcss';

@Component({
  selector: 'sg-blog_section',
  templateUrl: './blog_section.component.html',
  standalone: true,
  imports: [BrightnessDirective, TransformOriginDirective, TranslateYDirective, TextDecorationLineDirective, PaddingLeftDirective, WidthDirective, ColorBlueDirective, BackgroundPositionDirective, TransitionPropertyDirective, FlexBasisDirective, PaddingBottomDirective, BackgroundClipDirective, FontSizeDirective, BorderBottomWidthDirective, MaxWScreenDirective, MarginLeftDirective, BackgroundOrangeColorDirective, AlignItemsDirective, BackgroundSizeDirective, JustifyContentDirective, ColorNeutralDirective, PositionDirective, LineHeightDirective, MarginBottomDirective, TextTransformDirective, TextAlignDirective, SaturateDirective, FlexWrapDirective, ScaleYDirective, HueRotateDirective, InvertDirective, TransitionTimingFunctionDirective, PaddingTopDirective, VerticalAlignDirective, MaxWidthDirective, TransitionDurationDirective, MarginTopDirective, BorderStyleDirective, ContrastDirective, FlexGrowDirective, SepiaDirective, BorderBottomZincColorDirective, BackgroundImageDirective, FlexShrinkDirective, BackgroundRepeatDirective, GradientFromPositionDirective, PaddingRightDirective, OpacityDirective, ColorZincDirective, ColumnGapDirective, DisplayDirective, ColorDirective, OverflowDirective, MarginRightDirective, RowGapDirective, GradientFromOrangeDirective, FontWeightDirective]
})
export class BlogSectionComponent {}