import { Component } from '@angular/core';
import { ListStyleTypeDirective, BorderTopWidthDirective, BrightnessDirective, BorderRadiusDirective, BorderZincColorDirective, ColorOrangeDirective, TextDecorationLineDirective, PaddingLeftDirective, WidthDirective, ColorBlueDirective, TransitionPropertyDirective, PaddingBottomDirective, HeightDirective, BackgroundZincColorDirective, FontSizeDirective, BorderBottomWidthDirective, MaxWScreenDirective, BackgroundOrangeColorDirective, TopDirective, AlignItemsDirective, MarginLeftDirective, FontFamilyDirective, JustifyContentDirective, ColorNeutralDirective, PositionDirective, LineHeightDirective, MarginBottomDirective, TextTransformDirective, BorderBottomColorDirective, SaturateDirective, HueRotateDirective, FontStyleDirective, TransitionTimingFunctionDirective, InvertDirective, PaddingTopDirective, VerticalAlignDirective, MaxWidthDirective, MarginTopDirective, BorderStyleDirective, TransitionDurationDirective, BorderWidthDirective, FlexGrowDirective, BoxShadowDirective, BorderBottomZincColorDirective, AlignSelfDirective, RightDirective, ContrastDirective, SepiaDirective, GridColsDirective, ZIndexDirective, FlexDirectionDirective, PaddingRightDirective, ShadowZincColorDirective, BorderTopZincColorDirective, ColumnGapDirective, DisplayDirective, ColorDirective, OverflowDirective, LeftDirective, MarginRightDirective, CursorDirective, RowGapDirective, BackgroundColorDirective, BorderTopOrangeColorDirective, FontWeightDirective } from '@public-repo/tailwindcss';

@Component({
  selector: 'sg-header',
  templateUrl: './header.component.html',
  standalone: true,
  imports: [ListStyleTypeDirective, BorderTopWidthDirective, BrightnessDirective, BorderRadiusDirective, BorderZincColorDirective, ColorOrangeDirective, TextDecorationLineDirective, PaddingLeftDirective, WidthDirective, ColorBlueDirective, TransitionPropertyDirective, PaddingBottomDirective, HeightDirective, BackgroundZincColorDirective, FontSizeDirective, BorderBottomWidthDirective, MaxWScreenDirective, BackgroundOrangeColorDirective, TopDirective, AlignItemsDirective, MarginLeftDirective, FontFamilyDirective, JustifyContentDirective, ColorNeutralDirective, PositionDirective, LineHeightDirective, MarginBottomDirective, TextTransformDirective, BorderBottomColorDirective, SaturateDirective, HueRotateDirective, FontStyleDirective, TransitionTimingFunctionDirective, InvertDirective, PaddingTopDirective, VerticalAlignDirective, MaxWidthDirective, MarginTopDirective, BorderStyleDirective, TransitionDurationDirective, BorderWidthDirective, FlexGrowDirective, BoxShadowDirective, BorderBottomZincColorDirective, AlignSelfDirective, RightDirective, ContrastDirective, SepiaDirective, GridColsDirective, ZIndexDirective, FlexDirectionDirective, PaddingRightDirective, ShadowZincColorDirective, BorderTopZincColorDirective, ColumnGapDirective, DisplayDirective, ColorDirective, OverflowDirective, LeftDirective, MarginRightDirective, CursorDirective, RowGapDirective, BackgroundColorDirective, BorderTopOrangeColorDirective, FontWeightDirective]
})
export class HeaderComponent {}