import { Component } from '@angular/core';
import { ListStyleTypeDirective, BrightnessDirective, BorderRadiusDirective, TranslateYDirective, ColorOrangeDirective, TextDecorationLineDirective, PaddingLeftDirective, WidthDirective, ColorBlueDirective, TransitionPropertyDirective, FlexBasisDirective, PaddingBottomDirective, HeightDirective, BackgroundZincColorDirective, FontSizeDirective, MaxWScreenDirective, MarginLeftDirective, BackgroundOrangeColorDirective, TopDirective, AlignItemsDirective, FontFamilyDirective, JustifyContentDirective, ColorNeutralDirective, PositionDirective, LineHeightDirective, MarginBottomDirective, TextTransformDirective, TextAlignDirective, SaturateDirective, FlexWrapDirective, HueRotateDirective, TransitionTimingFunctionDirective, InvertDirective, PaddingTopDirective, VerticalAlignDirective, MaxWidthDirective, TransitionDurationDirective, MarginTopDirective, BorderWidthDirective, ContrastDirective, FlexGrowDirective, SepiaDirective, RightDirective, FlexShrinkDirective, RotateDirective, ZIndexDirective, FlexDirectionDirective, PaddingRightDirective, OpacityDirective, ColorZincDirective, ColumnGapDirective, DisplayDirective, ColorDirective, OverflowDirective, LeftDirective, MarginRightDirective, CursorDirective, RowGapDirective, BackgroundColorDirective, BottomDirective, FontWeightDirective } from '@public-repo/tailwindcss';

@Component({
  selector: 'sg-section_eight',
  templateUrl: './section_eight.component.html',
  standalone: true,
  imports: [ListStyleTypeDirective, BrightnessDirective, BorderRadiusDirective, TranslateYDirective, ColorOrangeDirective, TextDecorationLineDirective, PaddingLeftDirective, WidthDirective, ColorBlueDirective, TransitionPropertyDirective, FlexBasisDirective, PaddingBottomDirective, HeightDirective, BackgroundZincColorDirective, FontSizeDirective, MaxWScreenDirective, MarginLeftDirective, BackgroundOrangeColorDirective, TopDirective, AlignItemsDirective, FontFamilyDirective, JustifyContentDirective, ColorNeutralDirective, PositionDirective, LineHeightDirective, MarginBottomDirective, TextTransformDirective, TextAlignDirective, SaturateDirective, FlexWrapDirective, HueRotateDirective, TransitionTimingFunctionDirective, InvertDirective, PaddingTopDirective, VerticalAlignDirective, MaxWidthDirective, TransitionDurationDirective, MarginTopDirective, BorderWidthDirective, ContrastDirective, FlexGrowDirective, SepiaDirective, RightDirective, FlexShrinkDirective, RotateDirective, ZIndexDirective, FlexDirectionDirective, PaddingRightDirective, OpacityDirective, ColorZincDirective, ColumnGapDirective, DisplayDirective, ColorDirective, OverflowDirective, LeftDirective, MarginRightDirective, CursorDirective, RowGapDirective, BackgroundColorDirective, BottomDirective, FontWeightDirective]
})
export class SectionEightComponent {}