import { Component } from '@angular/core';
import { ColorOrangeDirective, TranslateYDirective, TextDecorationLineDirective, PaddingLeftDirective, WidthDirective, BackgroundPositionDirective, TransitionPropertyDirective, PaddingBottomDirective, HeightDirective, BackgroundZincColorDirective, FontSizeDirective, BackgroundSizeDirective, MaxWScreenDirective, MarginLeftDirective, AlignItemsDirective, BackgroundOrangeColorDirective, FontFamilyDirective, TopDirective, JustifyContentDirective, PositionDirective, LineHeightDirective, MarginBottomDirective, TextTransformDirective, TextAlignDirective, FontStyleDirective, TransitionTimingFunctionDirective, PaddingTopDirective, VerticalAlignDirective, MaxWidthDirective, TransitionDurationDirective, MarginTopDirective, BackgroundRepeatDirective, RightDirective, RotateDirective, ZIndexDirective, FlexDirectionDirective, PaddingRightDirective, OpacityDirective, ColorZincDirective, ColumnGapDirective, DisplayDirective, ColorDirective, LeftDirective, BackgroundAttachmentDirective, MarginRightDirective, CursorDirective, RowGapDirective, BackgroundColorDirective, FontWeightDirective } from '@public-repo/tailwindcss';

@Component({
  selector: 'sg-section_seven',
  templateUrl: './section_seven.component.html',
  standalone: true,
  imports: [ColorOrangeDirective, TranslateYDirective, TextDecorationLineDirective, PaddingLeftDirective, WidthDirective, BackgroundPositionDirective, TransitionPropertyDirective, PaddingBottomDirective, HeightDirective, BackgroundZincColorDirective, FontSizeDirective, BackgroundSizeDirective, MaxWScreenDirective, MarginLeftDirective, AlignItemsDirective, BackgroundOrangeColorDirective, FontFamilyDirective, TopDirective, JustifyContentDirective, PositionDirective, LineHeightDirective, MarginBottomDirective, TextTransformDirective, TextAlignDirective, FontStyleDirective, TransitionTimingFunctionDirective, PaddingTopDirective, VerticalAlignDirective, MaxWidthDirective, TransitionDurationDirective, MarginTopDirective, BackgroundRepeatDirective, RightDirective, RotateDirective, ZIndexDirective, FlexDirectionDirective, PaddingRightDirective, OpacityDirective, ColorZincDirective, ColumnGapDirective, DisplayDirective, ColorDirective, LeftDirective, BackgroundAttachmentDirective, MarginRightDirective, CursorDirective, RowGapDirective, BackgroundColorDirective, FontWeightDirective]
})
export class SectionSevenComponent {}