import { Component } from '@angular/core';
import { ColorOrangeDirective, TranslateYDirective, TextDecorationLineDirective, PaddingLeftDirective, WidthDirective, BackgroundPositionDirective, TransitionPropertyDirective, PaddingBottomDirective, HeightDirective, BackgroundZincColorDirective, FontSizeDirective, BackgroundSizeDirective, MaxWScreenDirective, MarginLeftDirective, BackgroundOrangeColorDirective, AlignItemsDirective, FontFamilyDirective, TopDirective, JustifyContentDirective, ColorNeutralDirective, PositionDirective, LineHeightDirective, MarginBottomDirective, TextTransformDirective, TextAlignDirective, FlexWrapDirective, FontStyleDirective, TransitionTimingFunctionDirective, PaddingTopDirective, VerticalAlignDirective, MaxWidthDirective, MarginTopDirective, TransitionDurationDirective, BackgroundRepeatDirective, FlexGrowDirective, RightDirective, FlexShrinkDirective, RotateDirective, FontWeightDirective, ZIndexDirective, FlexDirectionDirective, PaddingRightDirective, OpacityDirective, ColorZincDirective, ColumnGapDirective, DisplayDirective, ColorDirective, LeftDirective, BackgroundAttachmentDirective, MarginRightDirective, CursorDirective, RowGapDirective, BackgroundColorDirective, BottomDirective, FlexBasisDirective } from '@public-repo/tailwindcss';

@Component({
  selector: 'sg-curved_section',
  templateUrl: './curved_section.component.html',
  standalone: true,
  imports: [ColorOrangeDirective, TranslateYDirective, TextDecorationLineDirective, PaddingLeftDirective, WidthDirective, BackgroundPositionDirective, TransitionPropertyDirective, PaddingBottomDirective, HeightDirective, BackgroundZincColorDirective, FontSizeDirective, BackgroundSizeDirective, MaxWScreenDirective, MarginLeftDirective, BackgroundOrangeColorDirective, AlignItemsDirective, FontFamilyDirective, TopDirective, JustifyContentDirective, ColorNeutralDirective, PositionDirective, LineHeightDirective, MarginBottomDirective, TextTransformDirective, TextAlignDirective, FlexWrapDirective, FontStyleDirective, TransitionTimingFunctionDirective, PaddingTopDirective, VerticalAlignDirective, MaxWidthDirective, MarginTopDirective, TransitionDurationDirective, BackgroundRepeatDirective, FlexGrowDirective, RightDirective, FlexShrinkDirective, RotateDirective, FontWeightDirective, ZIndexDirective, FlexDirectionDirective, PaddingRightDirective, OpacityDirective, ColorZincDirective, ColumnGapDirective, DisplayDirective, ColorDirective, LeftDirective, BackgroundAttachmentDirective, MarginRightDirective, CursorDirective, RowGapDirective, BackgroundColorDirective, BottomDirective, FlexBasisDirective]
})
export class CurvedSectionComponent {}