import { CanActivate, ExecutionContext } from '@nestjs/common';
import { FirebaseAuthService } from '../_service/firebase/admin/auth.service';
import { FirestoreService } from '../_service/firebase/admin/firestore.service';
import { AccountService } from '../_service/firebase/admin/firestore/account.service';
import { BeneficiaryService } from '../_service/firebase/admin/firestore/beneficiary.service';
import { CompanyProfileService } from '../_service/firebase/admin/firestore/company-profile.service';
import { CustomerService } from '../_service/firebase/admin/firestore/customer.service';
import { EstimateService } from '../_service/firebase/admin/firestore/estimate.service';
import { ExpenseService } from '../_service/firebase/admin/firestore/expense.service';
import { InvoiceService } from '../_service/firebase/admin/firestore/invoice.service';
import { ItemService } from '../_service/firebase/admin/firestore/item.service';
import { JobLeadService } from '../_service/firebase/admin/firestore/job-lead.service';
import { JobService } from '../_service/firebase/admin/firestore/job.service';
import { PaymentService } from '../_service/firebase/admin/firestore/payment.service';
import { ProjectService } from '../_service/firebase/admin/firestore/project.service';
import { ProposalService } from '../_service/firebase/admin/firestore/proposal.service';
import { ProspectService } from '../_service/firebase/admin/firestore/prospect.service';
import { UserService } from '../_service/firebase/admin/firestore/user.service';
import { WorkServiceService } from '../_service/firebase/admin/firestore/work-service.service';
export declare class AuthGuard implements CanActivate {
    #private;
    private readonly accountsSvc;
    private readonly beneficiariesSvc;
    private readonly companyProfileSvc;
    private readonly customersSvc;
    private readonly estimatesSvc;
    private readonly expensesSvc;
    private readonly firebaseAuthSvc;
    private readonly firestoreSvc;
    private readonly invoicesSvc;
    private readonly itemsSvc;
    private readonly jobLeadsSvc;
    private readonly jobsSvc;
    private readonly paymentsSvc;
    private readonly projectsSvc;
    private readonly proposalsSvc;
    private readonly prospectsSvc;
    private readonly workServicesSvc;
    private readonly userSvc;
    constructor(accountsSvc: AccountService, beneficiariesSvc: BeneficiaryService, companyProfileSvc: CompanyProfileService, customersSvc: CustomerService, estimatesSvc: EstimateService, expensesSvc: ExpenseService, firebaseAuthSvc: FirebaseAuthService, firestoreSvc: FirestoreService, invoicesSvc: InvoiceService, itemsSvc: ItemService, jobLeadsSvc: JobLeadService, jobsSvc: JobService, paymentsSvc: PaymentService, projectsSvc: ProjectService, proposalsSvc: ProposalService, prospectsSvc: ProspectService, workServicesSvc: WorkServiceService, userSvc: UserService);
    canActivate(context: ExecutionContext): Promise<boolean>;
}
