export const serviceCities = [
  "Palm Beach",
  "West Palm Beach",
  "Boca Raton",
  "Delray Beach",
  "Palm Beach Gardens",
  "Boynton Beach",
  "Jupiter",
  "Lake Worth",
  "Wellington",
  "Royal Palm Beach",
  "North Palm Beach",
  "Palm Springs",
  "Riviera Beach",
  "Greenacres",
  "Juno Beach",
  "Tequesta",
  "Lake Park",
  "South Palm Beach",
  "Palm Beach Shores",
  "Atlantis",
];