import { ServiceCategory } from "@prisma/client";


export { ServiceCategory };

export const serviceCategoryMatchList: { [key: string]: ServiceCategory } = {
  "restore": ServiceCategory.Damage_Restoration,
  "damage": ServiceCategory.Damage_Restoration,
  "contractor": ServiceCategory.General_Contractor,
  "cleaning": ServiceCategory.Home_Cleaning,
  "plumb": ServiceCategory.Plumbing,
  "roof": ServiceCategory.Roofing,
  "carpet": ServiceCategory.Carpet_Installation,
  "decks": ServiceCategory.Decks_And_Railings,
  "rail": ServiceCategory.Decks_And_Railings,
  "drywall": ServiceCategory.Drywall,
  "concrete": ServiceCategory.Concrete,
  "pav": ServiceCategory.Paving,
  "insula": ServiceCategory.Insulation,
  "lock": ServiceCategory.Locksmith,
  "mason": ServiceCategory.Masonry,
  "patio": ServiceCategory.Patio_Coverings,
  "refinish": ServiceCategory.Refinishing,
  "stucco": ServiceCategory.Stucco,
  "window": ServiceCategory.Windows_And_Doors,
  "door": ServiceCategory.Windows_And_Doors,
  "electric": ServiceCategory.Electrical,
  "handy": ServiceCategory.Handyman,
  "inspect": ServiceCategory.Home_Inspector,
  "wash": ServiceCategory.Power_Washing,
  "pressure": ServiceCategory.Power_Washing,
  "demo": ServiceCategory.Demolition,
  "glass": ServiceCategory.Glass_And_Mirrors,
  "mirror": ServiceCategory.Glass_And_Mirrors,
  "landsca": ServiceCategory.Landscaping,
  "mobile home": ServiceCategory.Mobile_Home_Repair,
  "pool": ServiceCategory.Pool_And_Hot_Tub_Services,
  "sauna": ServiceCategory.Pool_And_Hot_Tub_Services,
  "hot tub": ServiceCategory.Pool_And_Hot_Tub_Services,
  "shutter": ServiceCategory.Shutters,
  "wallpaper": ServiceCategory.WallPapering,
  "floor": ServiceCategory.Flooring,
  "air condition": ServiceCategory.Air_Conditioning,
  "heat": ServiceCategory.Air_Conditioning,
  "paint": ServiceCategory.Painting,
  "tree": ServiceCategory.Tree_Services,
  "cabinet": ServiceCategory.Cabinetry,
  "counter": ServiceCategory.Countertop_Installation,
  "fence": ServiceCategory.Fences_And_Gates,
  "gate": ServiceCategory.Fences_And_Gates,
  "garage": ServiceCategory.Garage_Door_Services,
  "grout": ServiceCategory.Grout_Services,
  "irriga": ServiceCategory.Irrigation,
  "siding": ServiceCategory.Siding,
  "tile": ServiceCategory.Tiling,
  "tiling": ServiceCategory.Tiling,
  "garbage": ServiceCategory.Garbage_Removal,
  "junk": ServiceCategory.Garbage_Removal,
  "dump": ServiceCategory.Garbage_Removal,
  "laminat": ServiceCategory.Laminate_And_Hardwood_Flooring,
  "carpen": ServiceCategory.Carpentry,
  "secur": ServiceCategory.Security_Systems
};

export const serviceCategories = Object.values(serviceCategoryMatchList);
