export const m3Theme = {
  "primary": "#ff6600",
  "on-primary": "#fff",
  "primary-container": "#ff6600",
  "primary-fixed": "#ff6600",
  "primary-fixed-dim": "#ff6600",
  "on-primary-fixed": "#fff",
  "on-primary-fixed-variant": "#fff",
  "on-primary-container": "#fff",
  "secondary": "#0d6efd",
  "on-secondary": "#fff",
  "secondary-container": "#0d6efd",
  "secondary-fixed": "#0d6efd",
  "secondary-fixed-dim": "#0d6efd",
  "on-secondary-fixed": "#fff",
  "on-secondary-fixed-variant": "#fff",
  "on-secondary-container": "#fff",
  "on-surface": "#5b5b5b",
  "on-surface-variant": "rgba(0, 0, 0, 0.1)",
  "outline": "#d4d4d4",
  "outline-variant": "#5f5f5f",
  "scrim": "rgba(0, 0, 0, 0.1)",
  "error": "#DB222A",
  "error-container": "#DB222A",
  "on-error": "#fff",
  "on-error-container": "#fff",
  "surface": "#f6f6f6",
  "surface-container-lowest": "#e3e3e3",
  "surface-container-low": "#eff2f7",
  "surface-container": "#cdcdcd",
  "surface-container-high": "#d4d4d4",
  "font-family-primary": "'Montserrat', sans-serif",
  "font-family-secondary": "'Poppins', sans-serif",
  "font-family-accent": "'Montserrat', sans-serif",
  "display-large": "52px",
  "display-medium": "36px",
  "display-small": "36px",
  "headline-large": "52px",
  "headline-medium": "36px",
  "headline-small": "36px",
  "title-large": "30px",
  "title-medium": "24px",
  "title-small": "18px",
  "body-large": "25px",
  "body-medium": "16px",
  "body-small": "16px",
  "label-large": "14px",
  "label-medium": "14px",
  "label-small": "14px",
};

export type M3Theme = typeof m3Theme;