import { Component } from '@angular/core';
import { ListStyleTypeDirective, ColorOrangeDirective, TranslateYDirective, OutlineWidthDirective, TextDecorationLineDirective, PaddingLeftDirective, WidthDirective, TransitionPropertyDirective, PaddingBottomDirective, HeightDirective, BackgroundZincColorDirective, FontSizeDirective, BorderNeutralColorDirective, BorderBottomWidthDirective, MaxWScreenDirective, MarginLeftDirective, BackgroundOrangeColorDirective, AlignItemsDirective, FontFamilyDirective, TopDirective, JustifyContentDirective, ColorNeutralDirective, PositionDirective, LineHeightDirective, MarginBottomDirective, TextTransformDirective, TextAlignDirective, BorderBottomColorDirective, FlexWrapDirective, TransitionTimingFunctionDirective, FontStyleDirective, PaddingTopDirective, VerticalAlignDirective, MaxWidthDirective, MarginTopDirective, TransitionDurationDirective, BorderWidthDirective, BorderStyleDirective, FlexGrowDirective, RightDirective, FlexShrinkDirective, RotateDirective, FontWeightDirective, ZIndexDirective, FlexDirectionDirective, PaddingRightDirective, OpacityDirective, ColorZincDirective, ColumnGapDirective, DisplayDirective, ColorDirective, LeftDirective, MarginRightDirective, CursorDirective, RowGapDirective, BackgroundColorDirective, BottomDirective, FlexBasisDirective } from '@public-repo/tailwindcss';

@Component({
  selector: 'sg-section_four',
  templateUrl: './section_four.component.html',
  standalone: true,
  imports: [ListStyleTypeDirective, ColorOrangeDirective, TranslateYDirective, OutlineWidthDirective, TextDecorationLineDirective, PaddingLeftDirective, WidthDirective, TransitionPropertyDirective, PaddingBottomDirective, HeightDirective, BackgroundZincColorDirective, FontSizeDirective, BorderNeutralColorDirective, BorderBottomWidthDirective, MaxWScreenDirective, MarginLeftDirective, BackgroundOrangeColorDirective, AlignItemsDirective, FontFamilyDirective, TopDirective, JustifyContentDirective, ColorNeutralDirective, PositionDirective, LineHeightDirective, MarginBottomDirective, TextTransformDirective, TextAlignDirective, BorderBottomColorDirective, FlexWrapDirective, TransitionTimingFunctionDirective, FontStyleDirective, PaddingTopDirective, VerticalAlignDirective, MaxWidthDirective, MarginTopDirective, TransitionDurationDirective, BorderWidthDirective, BorderStyleDirective, FlexGrowDirective, RightDirective, FlexShrinkDirective, RotateDirective, FontWeightDirective, ZIndexDirective, FlexDirectionDirective, PaddingRightDirective, OpacityDirective, ColorZincDirective, ColumnGapDirective, DisplayDirective, ColorDirective, LeftDirective, MarginRightDirective, CursorDirective, RowGapDirective, BackgroundColorDirective, BottomDirective, FlexBasisDirective]
})
export class SectionFourComponent {}