import { Component } from '@angular/core';
import { GradientFromZincDirective, TranslateYDirective, ColorOrangeDirective, TextDecorationLineDirective, PaddingLeftDirective, WidthDirective, BorderRadiusDirective, BackgroundPositionDirective, TransitionPropertyDirective, PaddingBottomDirective, HeightDirective, BackgroundZincColorDirective, FontSizeDirective, BackgroundSizeDirective, MaxWScreenDirective, TopDirective, MarginLeftDirective, AlignItemsDirective, BackgroundOrangeColorDirective, FontFamilyDirective, JustifyContentDirective, TranslateXDirective, PositionDirective, LineHeightDirective, TextAlignDirective, MarginBottomDirective, TextTransformDirective, FlexWrapDirective, FontStyleDirective, TransitionTimingFunctionDirective, PaddingTopDirective, VerticalAlignDirective, MaxWidthDirective, MarginTopDirective, TransitionDurationDirective, BackgroundImageDirective, BackgroundRepeatDirective, FlexGrowDirective, BorderWidthDirective, ObjectPositionDirective, RightDirective, FlexShrinkDirective, RotateDirective, ZIndexDirective, FontWeightDirective, FlexDirectionDirective, PaddingRightDirective, OpacityDirective, ColumnGapDirective, DisplayDirective, ColorDirective, ObjectFitDirective, OverflowDirective, LeftDirective, MarginRightDirective, CursorDirective, RowGapDirective, BackgroundColorDirective, BottomDirective, ScaleDirective, FlexBasisDirective } from '@public-repo/tailwindcss';

@Component({
  selector: 'sg-section_one',
  templateUrl: './section_one.component.html',
  standalone: true,
  imports: [GradientFromZincDirective, TranslateYDirective, ColorOrangeDirective, TextDecorationLineDirective, PaddingLeftDirective, WidthDirective, BorderRadiusDirective, BackgroundPositionDirective, TransitionPropertyDirective, PaddingBottomDirective, HeightDirective, BackgroundZincColorDirective, FontSizeDirective, BackgroundSizeDirective, MaxWScreenDirective, TopDirective, MarginLeftDirective, AlignItemsDirective, BackgroundOrangeColorDirective, FontFamilyDirective, JustifyContentDirective, TranslateXDirective, PositionDirective, LineHeightDirective, TextAlignDirective, MarginBottomDirective, TextTransformDirective, FlexWrapDirective, FontStyleDirective, TransitionTimingFunctionDirective, PaddingTopDirective, VerticalAlignDirective, MaxWidthDirective, MarginTopDirective, TransitionDurationDirective, BackgroundImageDirective, BackgroundRepeatDirective, FlexGrowDirective, BorderWidthDirective, ObjectPositionDirective, RightDirective, FlexShrinkDirective, RotateDirective, ZIndexDirective, FontWeightDirective, FlexDirectionDirective, PaddingRightDirective, OpacityDirective, ColumnGapDirective, DisplayDirective, ColorDirective, ObjectFitDirective, OverflowDirective, LeftDirective, MarginRightDirective, CursorDirective, RowGapDirective, BackgroundColorDirective, BottomDirective, ScaleDirective, FlexBasisDirective]
})
export class SectionOneComponent {}