import { Component } from '@angular/core';
import { ColorOrangeDirective, TranslateYDirective, BorderRadiusDirective, TextDecorationLineDirective, PaddingLeftDirective, WidthDirective, BorderColorDirective, TransitionPropertyDirective, FlexBasisDirective, PaddingBottomDirective, HeightDirective, BackgroundZincColorDirective, FontSizeDirective, MaxWScreenDirective, MarginLeftDirective, BackgroundOrangeColorDirective, TopDirective, AlignItemsDirective, TranslateXDirective, FontFamilyDirective, JustifyContentDirective, ColorNeutralDirective, PositionDirective, LineHeightDirective, MarginBottomDirective, TextTransformDirective, TextAlignDirective, FlexWrapDirective, TransitionTimingFunctionDirective, FontStyleDirective, PaddingTopDirective, VerticalAlignDirective, MaxWidthDirective, TransitionDurationDirective, MarginTopDirective, BorderStyleDirective, BorderWidthDirective, FlexGrowDirective, RightDirective, FlexShrinkDirective, RotateDirective, ZIndexDirective, FlexDirectionDirective, PaddingRightDirective, OpacityDirective, ColorZincDirective, ColumnGapDirective, DisplayDirective, ColorDirective, OverflowDirective, LeftDirective, MarginRightDirective, CursorDirective, RowGapDirective, BackgroundColorDirective, BottomDirective, ScaleDirective, FontWeightDirective } from '@public-repo/tailwindcss';

@Component({
  selector: 'sg-section_two',
  templateUrl: './section_two.component.html',
  standalone: true,
  imports: [ColorOrangeDirective, TranslateYDirective, BorderRadiusDirective, TextDecorationLineDirective, PaddingLeftDirective, WidthDirective, BorderColorDirective, TransitionPropertyDirective, FlexBasisDirective, PaddingBottomDirective, HeightDirective, BackgroundZincColorDirective, FontSizeDirective, MaxWScreenDirective, MarginLeftDirective, BackgroundOrangeColorDirective, TopDirective, AlignItemsDirective, TranslateXDirective, FontFamilyDirective, JustifyContentDirective, ColorNeutralDirective, PositionDirective, LineHeightDirective, MarginBottomDirective, TextTransformDirective, TextAlignDirective, FlexWrapDirective, TransitionTimingFunctionDirective, FontStyleDirective, PaddingTopDirective, VerticalAlignDirective, MaxWidthDirective, TransitionDurationDirective, MarginTopDirective, BorderStyleDirective, BorderWidthDirective, FlexGrowDirective, RightDirective, FlexShrinkDirective, RotateDirective, ZIndexDirective, FlexDirectionDirective, PaddingRightDirective, OpacityDirective, ColorZincDirective, ColumnGapDirective, DisplayDirective, ColorDirective, OverflowDirective, LeftDirective, MarginRightDirective, CursorDirective, RowGapDirective, BackgroundColorDirective, BottomDirective, ScaleDirective, FontWeightDirective]
})
export class SectionTwoComponent {}